backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "post"
    label: "Post"
    folder: "src/pages/post"
    create: true
    slug: "{{title}}"
    identifier_field: name
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Create Page", name: "createPage", required: true, widget: "hidden", default: "true"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "relation", collection: "category", searchFields: ["title"], valueField: "title", displayFields: ["title"]}
      - {label: "Author", name: "author", widget: "relation", collection: "author", searchFields: ["name"], valueField: "name", displayFields: ["name"]}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Post", name: "featuredPost", widget: "boolean", default: false}
      - {label: "Category Featured Post", name: "categoryFeatured", widget: "boolean", default: false}
      - {label: "Trending Post", name: "trending", widget: "boolean", default: false}
      - {label: "Cover Image", name: "coverImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "subcategory-item"
    label: "Subcategory item"
    folder: "src/pages/categories"
    create: true
    path: "{{category}}/{{subcategory}}/{{title}}/{{slug}}"
    media_folder: /static/img
    public_folder: /img
    slug: "index"
    identifier_field: name
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "subcategory-item"}
      - {label: "Create Page", name: "createPage", required: true, widget: "hidden", default: "true"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "relation", collection: "category", searchFields: ["title"], valueField: "title", displayFields: ["title"]}
      - {label: "Subcategory", name: "subcategory", widget: "relation", collection: "subcategory", searchFields: ["title"], valueField: "title", displayFields: ["title"]}
      - {label: "Subcategory Featured Post", name: "subcategoryFeatured", widget: "boolean", default: false}
      - {label: "Cover Image", name: "coverImage", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "category"
    label: "Category"
    folder: "src/pages/categories"
    create: true
    path: "{{title}}/{{slug}}"
    media_folder: /static/img
    public_folder: /img
    slug: "index"
    identifier_field: name
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "category-page"}
      - {label: "Create Page", name: "createPage", required: true, widget: "hidden", default: "true"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Category Cover", name: "coverImage", widget: "image"}
      - {label: "Order on home page", name: "order", widget: "number"}
      - {label: "Order in navbar", name: "orderNavbar", widget: "number"}

  - name: "subcategory"
    label: "Subcategory"
    folder: "src/pages/categories"
    create: true
    path: "{{category}}/{{title}}/{{slug}}"
    media_folder: /static/img
    public_folder: /img
    slug: "index"
    identifier_field: name
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "category-subcategory"}
      - {label: "Create Page", name: "createPage", required: true, widget: "hidden", default: "true"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Subcategory Cover", name: "coverImage", widget: "image"}
      - {label: "Category", name: "category", widget: "relation", collection: "category", searchFields: ["title"], valueField: "title", displayFields: ["title"]}

  - name: "author"
    label: "Author"
    folder: "src/pages/author"
    create: true
    slug: "{{name}}"
    identifier_field: name
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "author-page"}
      - {label: "Create Page", name: "createPage", required: true, widget: "hidden", default: "true"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Author Information", name: "information", widget: "markdown"}
  
  - name: "otherSites"
    label: "Other Sites"
    folder: "src/data/other-sites"
    create: true
    slug: "{{title}}"
    identifier_field: name
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "other-sites-links"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "URL Address", name: "url", widget: "string"}
  
  - name: "socialLinks"
    label: "Social Links"
    folder: "src/data/social-links"
    create: true
    slug: "{{title}}"
    identifier_field: name
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "social-link"}
      - {label: 'Social Icon Dark', name: 'iconDark', widget: "image"}
      - {label: 'Social Icon Light', name: 'iconLight', widget: "image"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "URL Address", name: "url", widget: "string"}
      - {label: "Order", name: "order", widget: "number"}

  - name: "locations"
    label: "Locations"
    folder: "src/data/locations"
    create: true
    slug: "{{name}}"
    identifier_field: name
    fields: 
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "location"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Cover Image", name: "coverImage", widget: "image"}
      - {label: "Category", name: "category", widget: "relation", collection: "locationCategories", searchFields: ["title"], valueField: "title", displayFields: ["title"]}
      - {label: "Subcategory", name: "subcategory", widget: "relation", collection: "locationSubcategories", searchFields: ["title"], valueField: "title", displayFields: ["title"]}
      - {label: "Address", name: "address", widget: "string"}
      - {label: "Latitude", name: "latitude", widget: "string"}
      - {label: "Longitude", name: "longitude", widget: "string"}

  - name: "locationCategories"
    label: "Location Categories"
    folder: "src/data/location-categories"
    create: true
    slug: "{{title}}"
    identifier_field: name
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "location-category"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category Pin", name: "categoryPin", widget: "image"}
    
  - name: "locationSubcategories"
    label: "Location Subcategories"
    folder: "src/data/location-subcategory"
    create: true
    slug: "{{title}}"
    identifier_field: name
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "location-subcategory"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category Pin", name: "categoryPin", widget: "image"}
  
  - name: "shopProduct"
    label: "Shop Product"
    folder: "src/pages/shop/product"
    create: true
    path: "{{title}}/{{slug}}"
    media_folder: /static/img
    public_folder: /img
    slug: "index"
    identifier_field: name
    fields: 
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "shop-product"}
      - {label: "Title", name: "title", widget: string}
      - {label: "Description", name: "description", widget: string}
      - {label: "Category", name: "category", widget: relation, collection: "productCategory", searchFields: ["title"], valueField: "title", displayFields: ["title"]}
      - {label: "Images", name: "images", widget: list, fields: [
          {label: "Image", name: "image", widget: image}
      ]}
      - {label: "Price", name: "price", widget: number}
      - {label: "Sizes", name: "sizes", widget: list, fields: [
          {label: "Size", name: "size", widget: string},
          {label: "Size Available", name: "available", widget: boolean}
      ]}
      - {label: "Product Available", name: "available", widget: boolean}

  - name: "productCategory"
    label: "Product Category"
    folder: "src/data/product-category"
    create: true
    slug: "{{title}}"
    identifier_field: name
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-category"}
      - {label: "Title", name: "title", widget: "string"}
    
  - name: "logos"
    label: "Logos"
    folder: "src/data/logos"
    create: true
    slug: "{{title}}"
    identifier_field: name
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "logos"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Logo Image", name: "logoImage", widget: "image"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/shop/index.md"
        label: "Shop Page"
        name: "shopPage"
        fields:
          - {label: Banners, name: banners, widget: list, fields: [
              {label: "Banner Image", name: "bannerImage", widget: image},
              {label: "Banner Heading", name: "bannerHeading", widget: string},
              {label: "Banner Description", name: "bannerDescription", widget: string},
              {label: "Banner Button", name: "bannerButton", widget: list, fields: [
                {label: "Button Text", name: "buttonText", widget: string},
                {label: "Button Link", name: "buttonLink", widget: string}
              ]}
          ]}

      - file: "src/pages/work-with-us/index.md"
        label: "Work With Us Page"
        name: "workWithUsPage"
        fields:
          - {label: "Hero Video", name: "heroVideoCover", widget: file}
          - {label: "Hero Heading", name: heroHeading, widget: string}
          - {label: "Hero Text", name: "heroText", widget: string}
          - {label: "Hero Quote", name: "heroQuote", widget: string}
          - {label: "About Section Cover", name: "aboutImageCover", widget: image}
          - {label: "About Text", name: "aboutText", widget: markdown}
          - {label: "sections", name: "sections", widget: list, fields: [
              {label: "Section Cover", name: "coverImage", widget: image},
              {label: "Section Heading", name: "sectionHeading", widget: string},
              {label: "Section Text", name: "sectionText", widget: markdown}
          ]}
          - {label: "Template Key", name: "templateKey", widget: "string", default: "work-with-us-page"}

      - file: "src/pages/careers/index.md"
        label: "Careers Page"
        name: "careersPage"
        fields:
          - {label: Hero Image, name: heroImage, widget: image}
          - {label: "Slides", name: "slides", widget: list, fields: [
              {label: "Image",name: "image", widget: image}
          ]
            }
          - {label: "Benefits", name: "benefits", widget: list, fields: [
              {label: "Image" ,name: "image", widget: image},
              {label: "Text", name: "text", widget: markdown}
          ]
            }
          - {label: "Template Key", name: "templateKey", widget: "string", default: "careers-page"}

      - file: "src/pages/terms-of-use/index.md"
        label: "Terms Of Use Page"
        name: "termsOfUse"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: "markdown"}     
          - {label: "Template Key", name: "templateKey", widget: "string", default: "page-title-and-body"}

      - file: "src/pages/privacy-policy/index.md"
        label: "Privacy Policy"
        name: "privacyPolicy"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: "markdown"}     
          - {label: "Template Key", name: "templateKey", widget: "string", default: "page-title-and-body"}

      - file: "src/pages/contact-us/index.md"
        label: "Contact Us"
        name: "contactUs"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: "markdown"}     
          - {label: "Template Key", name: "templateKey", widget: "string", default: "page-title-and-body"}
